//[sqlcode.txt file time=2014/07/17 11:24:27]
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is generated by the sql header file tool sqlgen.exe. Please do 
// not modify this file directly. Change the sqlcode.txt file instead.
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 


#ifndef  __PROJECT_SQL_MACRO_DEF_H__          
#define __PROJECT_SQL_MACRO_DEF_H__           


//[0][SYS_SYSDATE_NOW]

//[0][SYS_SYSDATE_NOW]
//[[oracle]][[mysql]]
#define 	SYS_SYSDATE_NOW_SELECT_1000 	 "SYS_SYSDATE_NOW_SELECT_1000"
#define 	SYS_SYSDATE_NOW_SELECT_1001 	 "SYS_SYSDATE_NOW_SELECT_1001"
#define 	SYS_SYSDATE_NOW_SELECT_1002 	 "SYS_SYSDATE_NOW_SELECT_1002"
#define 	SYS_SYSDATE_NOW_SELECT_1003 	 "SYS_SYSDATE_NOW_SELECT_1003"

//[1][TABLE_TEST_DAITEST]
//[[common]]
#define 	TABLETESTDAITEST_SELECT_1000 	 "TABLETESTDAITEST_SELECT_1000"
#define 	TABLETESTDAITEST_SELECT_1001 	 "TABLETESTDAITEST_SELECT_1001"
#define 	TABLETESTDAITEST_UPDATE_3000 	 "TABLETESTDAITEST_UPDATE_3000"
#define 	TABLETESTDAITEST_DELETE_4000 	 "TABLETESTDAITEST_DELETE_4000"
#define 	TABLETESTDAITEST_DROP_5000 	 "TABLETESTDAITEST_DROP_5000"

//[1][TABLE_TEST_DAITEST]
//[[oracle]][[mysql]]
#define 	TABLETESTDAITEST_INSERT_2000 	 "TABLETESTDAITEST_INSERT_2000"
#define 	TABLETESTDAITEST_INSERT_2001 	 "TABLETESTDAITEST_INSERT_2001"
#define 	TABLETESTDAITEST_CREATE_6000 	 "TABLETESTDAITEST_CREATE_6000"
#define 	TABLETESTDAITEST_DELETE_4001 	 "TABLETESTDAITEST_DELETE_4001"


#endif//__PROJECT_SQL_MACRO_DEF_H__           

