/*-------------------------------------------------------------------------------------------------*/
DELIMITER $$

DROP PROCEDURE IF EXISTS `PRC_MY_LOG_INSERT` $$

CREATE PROCEDURE `PRC_MY_LOG_INSERT`(
	  IN p_LOG_LEVEL VARCHAR(128),
	  IN p_LOG_MSG_FUN VARCHAR(256),
	  IN p_LOG_MSG_STR0 VARCHAR(2048),
	  IN p_LOG_MSG_STR1 VARCHAR(2048),
	  IN p_LOG_MSG_STR2 VARCHAR(2048)
)
/*
CALL PRC_ADM_SEQUENCE_INSERT('INFO', 'FUN', 'p_LOG_MSG_STR0', 'p_LOG_MSG_STR1','p_LOG_MSG_STR2');
*/
BEGIN
	DECLARE	str_MY_LOG_SEQ	VARCHAR(30)	DEFAULT	'MY_LOG_SEQ';
	DECLARE	str_DATABASE_NAME	VARCHAR(30)	DEFAULT	NULL;
	DECLARE	str_location	VARCHAR(30)	DEFAULT	NULL;
	DECLARE str_TABLE_NAME VARCHAR(256)	DEFAULT	"MY_LOG";
	DECLARE str_COLUMN_NAME VARCHAR(1024)	DEFAULT	"LOG_PKEY, LOG_TIMESTAMP, LOG_LEVEL, LOG_MSG_FUN, LOG_MSG_STR0, LOG_MSG_STR1, LOG_MSG_STR2";
	DECLARE str_COLUMN_VALUE VARCHAR(8192)	DEFAULT	NULL;
	DECLARE str_SQL_INSERT VARCHAR(10240)	DEFAULT	NULL;

	SET str_COLUMN_VALUE = CONCAT(
	FUNC_SEQ_GET_NEXT_NUMBER(str_MY_LOG_SEQ), ',',
	'''', now(), '''', ',',
	'''', p_LOG_LEVEL, '''', ',',
	'''', p_LOG_MSG_FUN, '''', ',',
	'''', p_LOG_MSG_STR0, '''', ',',
	'''', p_LOG_MSG_STR1, '''', ',',
	'''', p_LOG_MSG_STR2, ''''
	);
	
	SET str_SQL_INSERT = FUNC_BASE_BUILD_SQL_INSERT(str_TABLE_NAME, str_COLUMN_NAME, str_COLUMN_VALUE);
	SET @G_SQL=NULL;
	SET @G_SQL=str_SQL_INSERT;
	
	-- insert data to CREATE_QUEUE 
	PREPARE stmt_SQL FROM @G_SQL;
	EXECUTE stmt_SQL;
	DEALLOCATE PREPARE stmt_SQL;
	set @G_SQL = null;

END $$

DELIMITER ;
/*-------------------------------------------------------------------------------------------------*/








/*-------------------------------------------------------------------------------------------------*/
DELIMITER $$

DROP PROCEDURE IF EXISTS `PRC_ADM_SEQUENCE_INSERT` $$

CREATE PROCEDURE `PRC_ADM_SEQUENCE_INSERT`(
	  IN p_SEQ_NAME VARCHAR(128),
	  IN p_INIT_NUMBER DECIMAL(30,0),
	  IN p_LAST_NUMBER DECIMAL(30,0),
	  IN p_MAX_NUMBER DECIMAL(30,0),
	  IN p_INCREMENT_BY INT(11),
	  IN p_CYCLE_FLAG VARCHAR(1)
)
/*
CALL PRC_ADM_SEQUENCE_INSERT('MY_LOG_SEQ', 0, 0, 18446744073709551610, 1, 'Y');
CALL PRC_ADM_SEQUENCE_INSERT('MY_LOG_SEQ', 0, 0, 2000000000, 1, 'Y');
*/
BEGIN
	DECLARE str_TABLE_NAME VARCHAR(256)	DEFAULT	"ADM_SEQUENCE";
	DECLARE str_COLUMN_NAME VARCHAR(1024)	DEFAULT	"SEQ_NAME, INIT_NUMBER, LAST_NUMBER, MAX_NUMBER, INCREMENT_BY, CYCLE_FLAG";
	DECLARE str_COLUMN_VALUE VARCHAR(8192)	DEFAULT	NULL;
	DECLARE str_SQL_INSERT VARCHAR(10240)	DEFAULT	NULL;

	SET str_COLUMN_VALUE = CONCAT(
	'''', p_SEQ_NAME, '''', ',',
	p_INIT_NUMBER, ',',
	p_LAST_NUMBER, ',',
	p_MAX_NUMBER, ',',
	p_INCREMENT_BY, ',',
	'''', p_CYCLE_FLAG, ''''
	);
	
	SET str_SQL_INSERT = FUNC_BASE_BUILD_SQL_INSERT(str_TABLE_NAME, str_COLUMN_NAME, str_COLUMN_VALUE);
	SET @G_SQL=NULL;
	SET @G_SQL=str_SQL_INSERT;
	
	-- insert data to CREATE_QUEUE 
	PREPARE stmt_SQL FROM @G_SQL;
	EXECUTE stmt_SQL;
	DEALLOCATE PREPARE stmt_SQL;
	set @G_SQL = null;

END $$

DELIMITER ;
/*-------------------------------------------------------------------------------------------------*/










/*-------------------------------------------------------------------------------------------------*/
DELIMITER $$

DROP PROCEDURE IF EXISTS `PRC_GET_QUEUE_INFO` $$

CREATE PROCEDURE `PRC_GET_QUEUE_INFO`(
	IN p_QUEUE_NAME      VARCHAR(128),
	OUT p_GET_SEQ_AQ_SAMPLE_QUEUE_NAME    VARCHAR(128),
	OUT p_GET_AQ_SAMPLE_QUEUE_NAME_T    VARCHAR(128),
	OUT p_GET_AQ_SAMPLE_QUEUE_NAME_T_I    VARCHAR(128),
	OUT p_GET_AQ_SAMPLE_QUEUE_NAME_T_S    VARCHAR(128)
)
	/*
	CALL PRC_DBMS_AQADM_CREATE_QUEUE('AUDIT_DATA_QUEUE');
	*/
BEGIN
	SET p_GET_SEQ_AQ_SAMPLE_QUEUE_NAME = CONCAT('AQ_', p_QUEUE_NAME, '_SEQ');
	SET p_GET_AQ_SAMPLE_QUEUE_NAME_T = CONCAT('AQ_', p_QUEUE_NAME, '_T');
	SET p_GET_AQ_SAMPLE_QUEUE_NAME_T_I = CONCAT('AQ_', p_QUEUE_NAME, '_T', '_I');
	SET p_GET_AQ_SAMPLE_QUEUE_NAME_T_S = CONCAT('AQ_', p_QUEUE_NAME, '_T', '_S');
END $$

DELIMITER ;
/*-------------------------------------------------------------------------------------------------*/








/*-------------------------------------------------------------------------------------------------*/
DELIMITER $$

DROP PROCEDURE IF EXISTS `PRC_DBMS_AQADM_CREATE_QUEUE` $$

CREATE PROCEDURE `PRC_DBMS_AQADM_CREATE_QUEUE`(
	IN p_QUEUE_NAME      VARCHAR(128)
)
	/*
	CALL PRC_DBMS_AQADM_CREATE_QUEUE('AUDIT_DATA_QUEUE');
	*/
BEGIN
	DECLARE str_QUEUE_NAME    VARCHAR(128) DEFAULT NULL;
	DECLARE str_QUEUE_TYPE    VARCHAR(256) DEFAULT NULL;
	DECLARE str_OBJECT_NAME    VARCHAR(256) DEFAULT NULL;
	DECLARE str_SEQ_AQ_SAMPLE_QUEUE_NAME    VARCHAR(128) DEFAULT NULL;
	DECLARE str_AQ_SAMPLE_QUEUE_NAME_T    VARCHAR(128) DEFAULT NULL;	
	DECLARE str_AQ_SAMPLE_QUEUE_NAME_T_I    VARCHAR(128) DEFAULT NULL;
	DECLARE str_AQ_SAMPLE_QUEUE_NAME_T_S    VARCHAR(128) DEFAULT NULL;
	DECLARE str_SQL_CREATE_AQ_SAMPLE_QUEUE_NAME_T   VARCHAR(1024) DEFAULT NULL;
	DECLARE str_SQL_CREATE_AQ_SAMPLE_QUEUE_NAME_T_I    VARCHAR(1024) DEFAULT NULL;
	DECLARE str_SQL_CREATE_AQ_SAMPLE_QUEUE_NAME_T_S    VARCHAR(1024) DEFAULT NULL;
	DECLARE str_SQL_CREATE_QUEUE_TABLES    VARCHAR(1024) DEFAULT NULL;
	

	SET str_QUEUE_NAME = p_QUEUE_NAME;
	SET str_QUEUE_TYPE = CONCAT('SYS.DBMS_AQADM.NORMAL_QUEUE');
	SET str_OBJECT_NAME = CONCAT('AUDIT_DATA_QUEUE_PAYLOAD_TYPE');
	CALL PRC_GET_QUEUE_INFO(str_QUEUE_NAME, str_SEQ_AQ_SAMPLE_QUEUE_NAME, str_AQ_SAMPLE_QUEUE_NAME_T, str_AQ_SAMPLE_QUEUE_NAME_T_I, str_AQ_SAMPLE_QUEUE_NAME_T_S);
	
	SET str_SQL_CREATE_AQ_SAMPLE_QUEUE_NAME_T = CONCAT('CREATE TABLE', ' ', str_AQ_SAMPLE_QUEUE_NAME_T, ' ', 'LIKE AQ_SAMPLE_QUEUE_NAME_T');/* DATA TABLE */
	SET str_SQL_CREATE_AQ_SAMPLE_QUEUE_NAME_T_I = CONCAT('CREATE TABLE', ' ', str_AQ_SAMPLE_QUEUE_NAME_T_I, ' ', 'LIKE AQ_SAMPLE_QUEUE_NAME_T_I');/*  */
	SET str_SQL_CREATE_AQ_SAMPLE_QUEUE_NAME_T_S = CONCAT('CREATE TABLE', ' ', str_AQ_SAMPLE_QUEUE_NAME_T_S, ' ', 'LIKE AQ_SAMPLE_QUEUE_NAME_T_s');/*  */
	SET str_SQL_CREATE_QUEUE_TABLES = CONCAT(
		str_SQL_CREATE_AQ_SAMPLE_QUEUE_NAME_T, ';',
		str_SQL_CREATE_AQ_SAMPLE_QUEUE_NAME_T_I, ';',
		str_SQL_CREATE_AQ_SAMPLE_QUEUE_NAME_T_S);
	
	
	-- CALL PRC_ADM_SEQUENCE_INSERT(str_SEQ_AQ_SAMPLE_QUEUE_NAME, 0, 0, 18446744073709551610, 1, 'Y');
	CALL PRC_ADM_SEQUENCE_INSERT(str_SEQ_AQ_SAMPLE_QUEUE_NAME, 0, 0, 2000000000, 1, 'Y');
		
	-- insert data to CREATE_QUEUE_RECORD 
	call PRC_CREATE_QUEUE_RECORD_INSERT(str_QUEUE_NAME, str_AQ_SAMPLE_QUEUE_NAME_T, str_QUEUE_TYPE, str_OBJECT_NAME, str_SQL_CREATE_QUEUE_TABLES);
	
	-- exec sql to create table 
	set @G_SQL = null;			
	set @G_SQL = str_SQL_CREATE_AQ_SAMPLE_QUEUE_NAME_T;
	PREPARE stmt_SQL FROM @G_SQL;
	EXECUTE stmt_SQL;
	DEALLOCATE PREPARE stmt_SQL	;
	set @G_SQL = null;

	
	-- exec sql to create table 
	set @G_SQL = null;			
	set @G_SQL = str_SQL_CREATE_AQ_SAMPLE_QUEUE_NAME_T_I;
	PREPARE stmt_SQL FROM @G_SQL;
	EXECUTE stmt_SQL;
	DEALLOCATE PREPARE stmt_SQL;
	set @G_SQL = null;
	
	-- exec sql to create table 
	set @G_SQL = null;			
	set @G_SQL = str_SQL_CREATE_AQ_SAMPLE_QUEUE_NAME_T_S;
	PREPARE stmt_SQL FROM @G_SQL;
	EXECUTE stmt_SQL;
	DEALLOCATE PREPARE stmt_SQL;
	set @G_SQL = null;
	
END $$

DELIMITER ;
/*-------------------------------------------------------------------------------------------------*/







