#ifndef  __DEF__PROJECT_DB_STRUCT_H__
#define  __DEF__PROJECT_DB_STRUCT_H__



//[DB begin]
static const char*  str_QtDbType_QSQLITE = "QSQLITE";
static const char*  str_QtDbType_QMYSQL = "QMYSQL";

//truncate a table in SQLite
//DELETE FROM someTable

//C:\LSL\LSL_DATA\SaveDataSqliteDB\000001.SZ
//C:\LSL\LSL_DATA\ServerDB\5000.db
//C:\LSL\LSL_DATA\ClientDB\UserNameValue_PassWordValue.db
//C:\LSL\LSL_DATA\ServerDB\STOCKSSQLITE_DB.db

/////
//C:\LSL\LSL_DATA\SaveDataSqliteDB\000001.SZ
//C:\LSL\LSL_DATA\ClientDB\UserNameValue_PassWordValue.db
//[[TABLE_BAR_DATA_1DAY]]
static const char*  str_TABLE_BAR_DATA_1DAY = "TABLE_BAR_DATA_1DAY";
//
static const char*  str_TABLE_BAR_DATA_COLUMN_SYMBOLUSE = "COLUMN_SYMBOLUSE";
static const char*  str_TABLE_BAR_DATA_Column_DATE = "COLUMN_DATE";
static const char*  str_TABLE_BAR_DATA_Column_OPEN = "COLUMN_OPEN";
static const char*  str_TABLE_BAR_DATA_Column_HIGH = "COLUMN_HIGH";
static const char*  str_TABLE_BAR_DATA_Column_LOW = "COLUMN_LOW";
static const char*  str_TABLE_BAR_DATA_Column_CLOSE = "COLUMN_CLOSE";
static const char*  str_TABLE_BAR_DATA_Column_VOLUME = "COLUMN_VOLUME";
static const char*  str_TABLE_BAR_DATA_Column_ADJCLOSE = "COLUMN_ADJCLOSE";

//C:\LSL\LSL_DATA\SaveDataSqliteDB\000001.SZ
//[[TABLE_SYMBOLUSE_MANAGER]]
static const char*  str_TABLE_SYMBOLUSE_MANAGER = "TABLE_SYMBOLUSE_MANAGER";
static const char*  str_TABLE_SYMBOLUSE_MANAGER_COLUMN_SYMBOLUSE = "COLUMN_SYMBOLUSE";
static const char*  str_TABLE_SYMBOLUSE_MANAGER_COLUMN_COLUMN_MAXTIME = "COLUMN_MAXTIME";
static const char*  str_TABLE_SYMBOLUSE_MANAGER_COLUMN_UPDATFAILED = "COLUMN_UPDATFAILED";


/////
//C:\LSL\LSL_DATA\ServerDB\5000.db
//[[TABLE_USER_INFO]]
static const char*  str_TABLE_USER_INFO = "TABLE_USER_INFO";
//
static const char*  str_TABLE_USER_INFO_COLUMN_USEID = "COLUMN_USEID";
static const char*  str_TABLE_USER_INFO_COLUMN_USERNAME = "COLUMN_USERNAME";
static const char*  str_TABLE_USER_INFO_COLUMN_PASSWORD = "COLUMN_PASSWORD";
static const char*  str_TABLE_USER_INFO_COLUMN_LASTLOGINTIME = "COLUMN_LASTLOGINTIME";
static const char*  str_TABLE_USER_INFO_COLUMN_LOGINCOUNT = "COLUMN_LOGINCOUNT";
static const char*  str_TABLE_USER_INFO_COLUMN_STATE = "COLUMN_STATE";

//C:\LSL\LSL_DATA\ServerDB\5000.db
//C:\LSL\LSL_DATA\ClientDB\UserNameValue_PassWordValue.db
//[[TABLE_USER_TRADE_INFO]]
static const char*  str_TABLE_USER_TRADE_INFO = "TABLE_USER_TRADE_INFO";
//
static const char*  str_TABLE_USER_TRADE_INFO_COLUMN_USEID = "COLUMN_USEID";
static const char*  str_TABLE_USER_TRADE_INFO_COLUMN_TRADE_UUID = "COLUMN_TRADE_UUID";
static const char*  str_TABLE_USER_TRADE_INFO_COLUMN_TRADE_TIME = "COLUMN_TRADE_TIME";
static const char*  str_TABLE_USER_TRADE_INFO_COLUMN_TRADE_TYPE = "COLUMN_TRADE_TYPE";
static const char*  str_TABLE_USER_TRADE_INFO_COLUMN_SYMBOLUSE = "COLUMN_SYMBOLUSE";
static const char*  str_TABLE_USER_TRADE_INFO_COLUMN_TRADE_PRICE = "COLUMN_TRADE_PRICE";
static const char*  str_TABLE_USER_TRADE_INFO_COLUMN_TRADE_VOLUME = "COLUMN_TRADE_VOLUME";
static const char*  str_TABLE_USER_TRADE_INFO_COLUMN_TRADE_AMOUNT = "COLUMN_TRADE_AMOUNT";
static const char*  str_TABLE_USER_TRADE_INFO_COLUMN_TRADE_FEES = "COLUMN_TRADE_FEES";
static const char*  str_TABLE_USER_TRADE_INFO_COLUMN_TOTAL_TRADE_FEE = "COLUMN_TOTAL_TRADE_FEE";
static const char*  str_TABLE_USER_TRADE_INFO_COLUMN_USE_ACCOUNT = "COLUMN_USE_ACCOUNT";

//C:\LSL\LSL_DATA\ServerDB\5000.db
//C:\LSL\LSL_DATA\ClientDB\UserNameValue_PassWordValue.db
//[[TABLE_USER_ACCOUNT]]
static const char*  str_TABLE_USER_ACCOUNT = "TABLE_USER_ACCOUNT";
//
static const char*  str_TABLE_USER_ACCOUNT_COLUMN_USEID = "COLUMN_USEID";
static const char*  str_TABLE_USER_ACCOUNT_COLUMN_INIT_ACCOUNT = "COLUMN_INIT_ACCOUNT";
static const char*  str_TABLE_USER_ACCOUNT_COLUMN_LEFT_ACCOUNT = "COLUMN_LEFT_ACCOUNT";
static const char*  str_TABLE_USER_ACCOUNT_COLUMN_HOLD_ACCOUNT = "COLUMN_HOLD_ACCOUNT";
static const char*  str_TABLE_USER_ACCOUNT_COLUMN_FLOATINT_PROFIT_LOSS = "COLUMN_FLOATINT_PROFIT_LOSS";//Floating profit and loss
static const char*  str_TABLE_USER_ACCOUNT_COLUMN_FLOATINT_PROFIT_LOSS_PERSENTAGE = "COLUMN_FLOATINT_PROFIT_LOSS_PERSENTAGE";//Floating profit and loss PERSENTAGE
static const char*  str_TABLE_USER_ACCOUNT_COLUMN_UPDATE_TIME = "COLUMN_UPDATE_TIME";

//C:\LSL\LSL_DATA\ServerDB\5000.db
//C:\LSL\LSL_DATA\ClientDB\UserNameValue_PassWordValue.db
//[[TABLE_USER_HOLD_ACCOUNT]]
static const char*  str_TABLE_USER_HOLD_ACCOUNT = "TABLE_USER_HOLD_ACCOUNT";
//
static const char*  str_TABLE_USER_HOLD_ACCOUNT_COLUMN_USERID = "COLUMN_USERID";
static const char*  str_TABLE_USER_HOLD_ACCOUNT_COLUMN_SYMBOLUSE = "COLUMN_SYMBOLUSE";
static const char*  str_TABLE_USER_HOLD_ACCOUNT_COLUMN_PRICE = "COLUMN_PRICE";
static const char*  str_TABLE_USER_HOLD_ACCOUNT_COLUMN_VOLUME = "COLUMN_VOLUME";
static const char*  str_TABLE_USER_HOLD_ACCOUNT_COLUMN_TIME = "COLUMN_TIME";
static const char*  str_TABLE_USER_HOLD_ACCOUNT_COLUMN_HOLD_ACCOUNT = "COLUMN_HOLDACCOUNT";
/////


//C:\LSL\LSL_DATA\ClientDB\UserNameValue_PassWordValue.db
//[[TABLE_MINTIME_MAXTIME]]
static const char*  str_TABLE_MINTIME_MAXTIME = "TABLE_MINTIME_MAXTIME";
static const char*  str_TABLE_MINTIME_MAXTIME_COLUMN_SYMBOLUSE = "COLUMN_SYMBOLUSE";
static const char*  str_TABLE_MINTIME_MAXTIME_COLUMN_MINTIME = "COLUMN_MINTIME";
static const char*  str_TABLE_MINTIME_MAXTIME_COLUMN_MAXTIME = "COLUMN_MAXTIME";
static const char*  str_TABLE_MINTIME_MAXTIME_COLUMN_COUNT = "COLUMN_COUNT";
static const char*  str_TABLE_MINTIME_MAXTIME_COLUMN_LOW = "COLUMN_LOW";
static const char*  str_TABLE_MINTIME_MAXTIME_COLUMN_HIGH = "COLUMN_HIGH";
static const char*  str_TABLE_MINTIME_MAXTIME_COLUMN_CURRENT = "COLUMN_CURRENT";
static const char*  str_TABLE_MINTIME_MAXTIME_COLUMN_CURRENTPERCENTAGE = "COLUMN_CURRENTPERCENTAGE";



//C:\LSL\LSL_DATA\ServerDB\STOCKSSQLITE_DB.db
static const char*  str_TABLE_STOCKSSQLITE = "TABLE_STOCKSSQLITE";
//
static const char*  str_TABLE_STOCKSSQLITE_COLUMN_SYMBOLUSE = "COLUMN_SYMBOLUSE";//"00001.SZ"
static const char*  str_TABLE_STOCKSSQLITE_COLUMN_NAMEPINYINFIRST = "COLUMN_NAMEPINYINFIRST";//"KDDL"
static const char*  str_TABLE_STOCKSSQLITE_COLUMN_NAMEPINYINFULL0 = "COLUMN_NAMEPINYINFULL0";//"Kai3 Di2 Dian4 Li4"
static const char*  str_TABLE_STOCKSSQLITE_COLUMN_NAMEPINYINFULL4 = "COLUMN_NAMEPINYINFULL4";//"Kai Di Dian Li"
static const char*  str_TABLE_STOCKSSQLITE_COLUMN_NAMEUTF8 = "COLUMN_NAMEUTF8";//nvarchar, Sqlite3 default use UTF8




#endif  // __DEF__PROJECT_DB_STRUCT_H__








