CREATE TABLE AQ_DEQ_TOKEN_CHECK
(
  PKEY          NUMBER(10)	NOT NULL,
  LOCATION  	VARCHAR2(80 BYTE)	NOT NULL,
  SRV_ID	NUMBER(5)	DEFAULT 0,
  Q_NAME	VARCHAR2(80 BYTE)	NOT NULL,
  UPD_TIME	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP 
)
TABLESPACE CONFIG_DATA;

CREATE UNIQUE INDEX AQ_DEQ_TOKEN_CHECK_PK ON AQ_DEQ_TOKEN_CHECK
(PKEY)
TABLESPACE CONFIG_INDX;

ALTER TABLE AQ_DEQ_TOKEN_CHECK ADD (
  CONSTRAINT AQ_DEQ_TOKEN_CHECK_PK
 PRIMARY KEY
 (PKEY)
    USING INDEX AQ_DEQ_TOKEN_CHECK_PK);

CREATE TABLE AQ_ENQ_DUPLICATE_CHECK
(
  PKEY          NUMBER(10)	NOT NULL,
  LOCATION	VARCHAR2(80 BYTE)	NOT NULL,
  SRV_ID	NUMBER(5)	DEFAULT 0,
  Q_NAME	VARCHAR2(80 BYTE)	NOT NULL,
  MSG_SID       NUMBER(20)	DEFAULT 0
)
TABLESPACE CONFIG_DATA;

CREATE UNIQUE INDEX AQ_ENQ_DUPLICATE_CHECK_PK ON AQ_ENQ_DUPLICATE_CHECK
(PKEY)
TABLESPACE CONFIG_INDX;

ALTER TABLE AQ_ENQ_DUPLICATE_CHECK ADD (
  CONSTRAINT AQ_ENQ_DUPLICATE_CHECKPK
 PRIMARY KEY
 (PKEY)
    USING INDEX AQ_ENQ_DUPLICATE_CHECK_PK);