CREATE SEQUENCE AQ_ENQ_DUP_CHECK_SEQ
  START WITH 1
  MAXVALUE 2147483647
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE SEQUENCE AQ_DEQ_TOKEN_CHECK_SEQ
  START WITH 1
  MAXVALUE 2147483647
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

truncate table AQ_DEQ_TOKEN_CHECK;

ALTER TABLE AQ_DEQ_TOKEN_CHECK ADD (
  CONSTRAINT AQ_DEQ_TOKEN_CHECK_U01
 UNIQUE (LOCATION, SRV_ID, Q_NAME));

truncate table AQ_ENQ_DUPLICATE_CHECK;

ALTER TABLE AQ_ENQ_DUPLICATE_CHECK ADD (
  CONSTRAINT AQ_ENQ_DUPLICATE_CHECK_U01
 UNIQUE (LOCATION, SRV_ID, Q_NAME));


create or replace trigger AQ_DEQ_TOKEN_CHECK_BIR_TRG
 before insert on AQ_DEQ_TOKEN_CHECK for each row
begin
  select AQ_DEQ_TOKEN_CHECK_SEQ.nextval into :NEW.pkey from dual;
end;
/    

create or replace trigger AQ_ENQ_DUPLICATE_CHECK_BIR_TRG
 before insert on AQ_ENQ_DUPLICATE_CHECK for each row
begin
  select AQ_ENQ_DUP_CHECK_SEQ.nextval into :NEW.pkey from dual;
end;
/    
